//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fafalymo.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fafalymo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Index,0 [0x0][0x0],1 [0x2][0x8],2 [0x0][0x4],3 [0x2][0x9],4 [0x2][0xa],5 [0x2][0xb],6 [0x2][0xc],7 [0x2][0xd]
        ///0,&quot;&quot;,0,&quot;&quot;,0,0,1,0,0
        ///1,&quot;&quot;,0,&quot;&quot;,0,0,0,0,0
        ///2,&quot;ruins runner&quot;,0,&quot;ruins runners&quot;,0,0,1,0,0
        ///3,&quot;antelope doe&quot;,0,&quot;antelope does&quot;,0,1,1,0,0
        ///4,&quot;antelope stag&quot;,0,&quot;antelope stags&quot;,0,1,1,0,0
        ///5,&quot;opo-opo&quot;,0,&quot;opo-opos&quot;,0,1,1,0,0
        ///6,&quot;lemur&quot;,0,&quot;lemurs&quot;,0,0,1,0,0
        ///7,&quot;giant gnat&quot;,0,&quot;giant gnats&quot;,0,0,1,0,0
        ///8,&quot;ked&quot;,0,&quot;keds&quot;,0,0,1,0,0
        ///9,&quot;miteling&quot;,0,&quot;mitelings&quot;,0,0,1,0,0
        ///10,&quot;diremite&quot;,0,&quot;diremites&quot;,0,0,1,0,0
        ///11,&quot;[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string bnpcname_exh_en {
            get {
                return ResourceManager.GetString("bnpcname_exh_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index,0 [0x0][0x0],1 [0x2][0x8],2 [0x0][0x4],3 [0x2][0x9],4 [0x2][0xa],5 [0x2][0xb],6 [0x2][0xc],7 [0x2][0xd]
        ///0,&quot;&quot;,0,&quot;&quot;,0,0,1,0,0
        ///1,&quot;&quot;,0,&quot;&quot;,0,0,0,0,0
        ///2,&quot;유적 랍토르&quot;,0,&quot;&quot;,0,0,1,0,0
        ///3,&quot;암영양&quot;,0,&quot;&quot;,0,0,1,0,0
        ///4,&quot;수영양&quot;,0,&quot;&quot;,0,0,1,0,0
        ///5,&quot;오포오포&quot;,0,&quot;&quot;,0,0,1,0,0
        ///6,&quot;여우원숭이&quot;,0,&quot;&quot;,0,0,1,0,0
        ///7,&quot;각다귀&quot;,0,&quot;&quot;,0,0,1,0,0
        ///8,&quot;말파리&quot;,0,&quot;&quot;,0,0,1,0,0
        ///9,&quot;작은 거미전갈&quot;,0,&quot;&quot;,0,0,1,0,0
        ///10,&quot;거미전갈&quot;,0,&quot;&quot;,0,0,1,0,0
        ///11,&quot;독거미전갈&quot;,0,&quot;&quot;,0,0,1,0,0
        ///12,&quot;대머리수리&quot;,0,&quot;&quot;,0,0,1,0,0
        ///13,&quot;독수리&quot;,0,&quot;&quot;,0,0,1,0,0
        ///14,&quot;야생 어린멧돼지&quot;,0,&quot;&quot;,0,0,1,0,0
        ///15,&quot;야생 수퇘지&quot;,0,&quot;&quot;,0,0,1[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string bnpcname_exh_ko {
            get {
                return ResourceManager.GetString("bnpcname_exh_ko", resourceCulture);
            }
        }
    }
}
